Description:  This template deploys IAM resources for Badgevent

Parameters:
  pEnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String

Resources:

  rKeyPair:
    Type: AWS::EC2::KeyPair
    Properties: 
      KeyName: !Ref pEnvironmentName
      KeyType: rsa
      PublicKeyMaterial: !Ref pPublicKey

  rDevServerEc2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: !Sub "${pEnvironmentName}DevServer"
      Path: /
      Roles: 
       - !Ref rDevServerEc2InstanceRole

  rWebServerEc2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: !Sub "${pEnvironmentName}WebServer"
      Path: /
      Roles: 
       - !Ref rWebServerEc2InstanceRole

  rWebServerEc2InstanceRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Description: Role to be used as an Instance Profile for Web Servers
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/AmazonRDSDataFullAccess
        - arn:aws:iam::aws:policy/AmazonElasticFileSystemClientReadOnlyAccess
      RoleName: !Sub "${pEnvironmentName}WebServerRole"

  rDevServerEc2InstanceRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Description: Role to be used as an Instance Profile for the Dev Server
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/AmazonRDSDataFullAccess
        - arn:aws:iam::aws:policy/AmazonElasticFileSystemClientReadWriteAccess
      RoleName: !Sub "${pEnvironmentName}DevServerRole"
